const MockDatabase = (list) => {


    //role is either officer, member or  admin?
    const users = [
        {id:1,
        firstName: "Charlie",
        lastName: "David",
        studentId: "222222",
        email:"CD@hsestudents.org",
        phoneNumber: "",
        emergencyContact: "111111111",
        dateOfBirth: "02/20/2005",
        grade: "freshman",
        tutoringHours: "2",
        serviceHours: "4",
        serviceProjects: "2",
        role: "member",
        tutoringClasses: ["Algebra 1, Chemistry, English 9"],
        paidDues: true,
        notifyBy: ["email, phone"],
        },
        {id:2,
            firstName: "Charlie",
            lastName: "David",
            studentId: "222222",
            email:"CD@hsestudents.org",
            phoneNumber: "",
            emergencyContact: "111111111",
            dateOfBirth: "02/20/2005",
            grade: "freshman",
            tutoringHours: "2",
            serviceHours: "4",
            serviceProjects: "2",
            role: "member",
            tutoringClasses: ["Algebra 1, Chemistry, English 9"],
            paidDues: true,
            notifyBy: ["email, phone"],
            },
            {id:3,
                firstName: "Charlie",
                lastName: "David",
                studentId: "222222",
                email:"CD@hsestudents.org",
                phoneNumber: "",
                emergencyContact: "111111111",
                dateOfBirth: "02/20/2005",
                grade: "freshman",
                tutoringHours: "2",
                serviceHours: "4",
                serviceProjects: "2",
                role: "member",
                tutoringClasses: ["Algebra 1, Chemistry, English 9"],
                paidDues: true,
                notifyBy: ["email, phone"],
                },
                {id:4,
                    firstName: "Charlie",
                    lastName: "David",
                    studentId: "222222",
                    email:"CD@hsestudents.org",
                    phoneNumber: "",
                    emergencyContact: "111111111",
                    dateOfBirth: "02/20/2005",
                    grade: "freshman",
                    tutoringHours: "2",
                    serviceHours: "4",
                    serviceProjects: "2",
                    role: "member",
                    tutoringClasses: ["Algebra 1, Chemistry, English 9"],
                    paidDues: true,
                    notifyBy: ["email, phone"],
                    },
                    {id:5,
                        firstName: "Charlie",
                        lastName: "David",
                        studentId: "222222",
                        email:"CD@hsestudents.org",
                        phoneNumber: "",
                        emergencyContact: "111111111",
                        dateOfBirth: "02/20/2005",
                        grade: "freshman",
                        tutoringHours: "2",
                        serviceHours: "4",
                        serviceProjects: "2",
                        role: "member",
                        tutoringClasses: ["Algebra 1, Chemistry, English 9"],
                        paidDues: true,
                        notifyBy: ["email, phone"],
                        },
                        {id:6,
                            firstName: "Charlie",
                            lastName: "David",
                            studentId: "222222",
                            email:"CD@hsestudents.org",
                            phoneNumber: "",
                            emergencyContact: "111111111",
                            dateOfBirth: "02/20/2005",
                            grade: "freshman",
                            tutoringHours: "2",
                            serviceHours: "4",
                            serviceProjects: "2",
                            role: "member",
                            tutoringClasses: ["Algebra 1, Chemistry, English 9"],
                            paidDues: true,
                            notifyBy: ["email, phone"],
                            },
                            {id:7,
                                firstName: "Charlie",
                                lastName: "David",
                                studentId: "222222",
                                email:"CD@hsestudents.org",
                                phoneNumber: "",
                                emergencyContact: "111111111",
                                dateOfBirth: "02/20/2005",
                                grade: "freshman",
                                tutoringHours: "2",
                                serviceHours: "4",
                                serviceProjects: "2",
                                role: "member",
                                tutoringClasses: ["Algebra 1, Chemistry, English 9"],
                                paidDues: true,
                                notifyBy: ["email, phone"],
                                },
                                {id:8,
                                    firstName: "Charlie",
                                    lastName: "David",
                                    studentId: "222222",
                                    email:"CD@hsestudents.org",
                                    phoneNumber: "",
                                    emergencyContact: "111111111",
                                    dateOfBirth: "02/20/2005",
                                    grade: "freshman",
                                    tutoringHours: "2",
                                    serviceHours: "4",
                                    serviceProjects: "2",
                                    role: "member",
                                    tutoringClasses: ["Algebra 1, Chemistry, English 9"],
                                    paidDues: true,
                                    notifyBy: ["email, phone"],
                                    },
                                    {id:9,
                                        firstName: "Charlie",
                                        lastName: "David",
                                        studentId: "222222",
                                        email:"CD@hsestudents.org",
                                        phoneNumber: "",
                                        emergencyContact: "111111111",
                                        dateOfBirth: "02/20/2005",
                                        grade: "freshman",
                                        tutoringHours: "2",
                                        serviceHours: "4",
                                        serviceProjects: "2",
                                        role: "member",
                                        tutoringClasses: ["Algebra 1, Chemistry, English 9"],
                                        paidDues: true,
                                        notifyBy: ["email, phone"],
                                        },
                                        {id:10,
                                            firstName: "Charlie",
                                            lastName: "David",
                                            studentId: "222222",
                                            email:"CD@hsestudents.org",
                                            phoneNumber: "",
                                            emergencyContact: "111111111",
                                            dateOfBirth: "02/20/2005",
                                            grade: "freshman",
                                            tutoringHours: "2",
                                            serviceHours: "4",
                                            serviceProjects: "2",
                                            role: "member",
                                            tutoringClasses: ["Algebra 1, Chemistry, English 9"],
                                            paidDues: true,
                                            notifyBy: ["email, phone"],
                                            },
                                            {id:11,
                                                firstName: "Charlie",
                                                lastName: "David",
                                                studentId: "222222",
                                                email:"CD@hsestudents.org",
                                                phoneNumber: "",
                                                emergencyContact: "111111111",
                                                dateOfBirth: "02/20/2005",
                                                grade: "freshman",
                                                tutoringHours: "2",
                                                serviceHours: "4",
                                                serviceProjects: "2",
                                                role: "member",
                                                tutoringClasses: ["Algebra 1, Chemistry, English 9"],
                                                paidDues: true,
                                                notifyBy: ["email, phone"],
                                                },
    ]


    const userSchedule = [
        {type: "Meeting",
        title: "NHS Monthly Meeting!!", 
        date:"02/22/2022", 
        times: ["8:00 am", "3:15 pm"], 
        location: "Lecture Hall", 
        names: ["Kari Richardson, Joanna Peters"], 
        contacts: ["kjricharson@hse.k12.in.us","jcpeters@hse.k12.in.us"],
        link: "Here is a link to the pp if you cant attend",
        notifications: [],
        tutoringInfo: {subjects: [], types: []},
        comment: "More Info on Future Service Projects at this meeting, must attend",
        },
        {type: "Tutoring",
        title: "Tutoring", 
        date:"02/27/2022", 
        times: ["8:30 am"], 
        location: "Media Center", 
        names: ["Mari Lily", "Dani Lily"], 
        contacts: ["lilymar@hsestudents.org,danimar@hsestudents.org"],
        link: "",
        notifications: [],
        tutoringInfo: {subjects: ["Algebra", "Chemistry"], types: ["Test Review, Project"]},
        comment: "",
        },
        {type: "Tutoring",
        title: "Tutoring", 
        date:"02/29/2022", 
        times: ["5:50 pm"], 
        location: "Zoom", 
        names: ["Jason Carl"], 
        contacts: ["630-111-1111, carljas@hsestudents.org"],
        link: "Here is a link to a zoom metting",
        notifications: [],
        tutoringInfo: {subjects: ["English 9"], types: ["Essay"]},
        comment: "pw and all other info to get into zoom",
        },
        {type: "Event",
        title: "Street Clean Up!!", 
        date:"02/28/2022", 
        times: ["3:20 pm"], 
        location: "Door 1 HSE", 
        names: ["Bill Blake, Cammron Byle"], 
        contacts: ["999-111-1111, bb@gmail.com"],
        link: "",
        notifications: [],
        tutoringInfo: {subjects: [], types: []},
        comment: "Trash pick up, wear appropriate attire for weather, etc.",
        },
    ]



    if(list === "users"){
        return users
    }
    else{
        return userSchedule
    }
    
}

export default MockDatabase